[project]
name = "data-warehouse"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dlt[postgres]>=1.16.0",
    "sqlmesh[postgres]>=0.216.0",
]
