# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

# @see: https://docs.docker.com/compose/how-tos/multiple-compose-files/include/
include:
  - ./compose-metabase.yaml

services:
  pgsql:
    image: postgres:17-alpine
    container_name: ${PROJECT_NAME}_pgsql
    hostname: postgres
    restart: unless-stopped
    ports:
      - 5432:${POSTGRES_PORT}
    volumes:
      - pgsql_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    command: ["postgres", "-c", "wal_level=logical"]
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d myorg"]
      interval: 30s
      timeout: 20s
      retries: 3

  pgweb:
    image: sosedoff/pgweb:latest
    container_name: ${PROJECT_NAME}_pgweb
    restart: always
    ports:
      - 54321:${PGWEB_PORT}
    environment:
      PGWEB_DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@pgsql:5432/${POSTGRES_DB}?sslmode=disable"
    depends_on:
      pgsql:
        condition: service_started

volumes:
  pgsql_data:
    name: ${PROJECT_NAME}_pgsql_data
    driver: local
