# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
# https://www.metabase.com/docs/latest/installation-and-operation/running-metabase-on-docker

services:
  metabase:
    image: metabase/metabase:latest
    container_name: ${PROJECT_NAME}_metabase
    hostname: metabase
    restart: unless-stopped
    volumes:
      - /dev/urandom:/dev/random:ro
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabaseappdb
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: mysecretpassword
      MB_DB_HOST: postgres
    networks:
      - metanet1
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 5s
      timeout: 5s
      start_period: 5s
      retries: 5
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgres:
    image: postgres:latest
    container_name: ${PROJECT_NAME}_metabase_postgres
    hostname: postgres
    volumes:
      - metabase_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: metabase
      POSTGRES_DB: metabaseappdb
      POSTGRES_PASSWORD: mysecretpassword
    networks:
      - metanet1
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U metabase -d metabaseappdb"]
      interval: 30s
      timeout: 20s
      retries: 3

networks:
  metanet1:
    driver: bridge

volumes:
  metabase_data:
    name: ${PROJECT_NAME}_metabase_pgsql_data
    driver: local
